menu:
  Home: /
  Archives: /archives

# AddToAny Share. See: https://www.addtoany.com
addtoany:
  enable: false
  buttons:
    - facebook
    - twitter

facebook:
twitter:
github:

fancybox: true
google_analytics:
rss:
# Display a "Read More" link under each post's excerpt in /archives page
#excerpt_link: 'Read More'

disqus_shortname:
